version: '3.0'
services:
  cassandra-server:
    image: cassandra:latest
    container_name: 'cassandra-server-iot'
    hostname: 'cassandra-server1'
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - ./scripts:/scripts
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-server1
      - CASSANDRA_CLUSTER_NAME=Digitalisevent
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=128
#    networks:
#      - kafka_net
  cassandra-init:
    image: cassandra:latest
    hostname: init
    volumes:
      - ./scripts:/scripts
    command: /scripts/cassandra-init-seed-data.sh && /bin/bash
    depends_on:
      cassandra-server:
        condition: service_healthy
    restart: "no"
#    networks:
#      - kafka_net
  API:
    image: 'iot-data-test-api'
    ports:
      - "9090:9090"
    depends_on:
      cassandra-server:
        condition: service_healthy
    environment:
      - SPRING.DATA.CASSANDRA.KEYSPACE-NAME=iot_data
      - SPRING.DATA.CASSANDRA.CONTACT-POINTS=host.docker.internal
      - SPRING.DATA.CASSANDRA.PORT=9042
      - SPRING.DATA.CASSANDRA.LOCAL-DATACENTER=DC1
      - SPRING.DATA.CASSANDRA.SCHEMA-ACTION=create_if_not_exists
      - SPRING.JPA.SHOW-SQL=true
      - kafka.bootstrapAddress=iot-producer-simulator-api-master_kafka_1_1:29093
      - general.topic.name=iot-data
      -  general.topic.group.id=group_id
      - spring.kafka.consumer.enable-auto-commit=false
      -  spring.kafka.listener.concurrency=5
      -  spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
      -  spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.LongDeserializer
      -  spring.kafka.listener.ack-mode=manual_immediate
      -  spring.data.cassandra.keyspace-name=iot_data
      -  spring.data.cassandra.contact-points=localhost
      -  spring.data.cassandra.port=9042
      -  spring.data.cassandra.local-datacenter=DC1
      -  spring.data.cassandra.schema-action=create_if_not_exists
      -  spring.jpa.show-sql=true
      -  spring.security.user.name=admin
      -  spring.security.user.password=root
#    networks:
#      - kafka_net
#networks:
#  kafka_net:
#    external:
#      name: iot-producer-simulator-api-master_app-network

